//CANDIDATOS
export const AGREGAR_CANDIDATO = "AGREGAR_CANDIDATO";
export const AGREGAR_CANDIDATO_EXITO = "AGREGAR_CANDIDATO_EXITO";
export const AGREGAR_CANDIDATO_ERROR = "AGREGAR_CANDIDATO_ERROR";
export const COMENZAR_DESCARGA_CANDIDATOS = "COMENZAR_DESCARGA_CANDIDATOS";
export const DESCARGA_CANDIDATOS_EXITOS = "DESCARGA_CANDIDATOS_EXITOS";
export const DESCARGA_CANDIDATOS_ERROR = "DESCARGA_CANDIDATOS_ERROR";
export const OBTENER_CANDIDATO_ELIMINAR = "OBTENER_CANDIDATO_ELIMINAR";
export const CANDIDATO_ELIMINADO_EXITO = "CANDIDATO_ELIMINADO_EXITO";
export const CANDIDATO_ELIMINADO_ERROR = "CANDIDATO_ELIMINADO_ERROR";

//USUARIOS
export const AGREGAR_USUARIO = "AGREGAR_USUARIO";
export const AGREGAR_USUARIO_EXITO = "AGREGAR_USUARIO_EXITO";
export const AGREGAR_USUARIO_ERROR = "AGREGAR_USUARIO_ERROR";
export const COMENZAR_DESCARGA_USUARIOS = "COMENZAR_DESCARGA_USUARIOS";
export const DESCARGA_USUARIOS_EXITOS = "DESCARGA_USUARIOS_EXITOS";
export const DESCARGA_USUARIOS_ERROR = "DESCARGA_USUARIOS_ERROR";
export const OBTENER_USUARIO_ELIMINAR = "OBTENER_USUARIO_ELIMINAR";
export const USUARIO_ELIMINADO_EXITO = "USUARIO_ELIMINADO_EXITO";
export const USUARIO_ELIMINADO_ERROR = "USUARIO_ELIMINADO_ERROR";
