//CANDIDATOS
export const AGREGAR_CANDIDATO = "AGREGAR_CANDIDATO";
export const AGREGAR_CANDIDATO_EXITO = "AGREGAR_CANDIDATO_EXITO";
export const AGREGAR_CANDIDATO_ERROR = "AGREGAR_CANDIDATO_ERROR";
export const COMENZAR_DESCARGA_CANDIDATOS = "COMENZAR_DESCARGA_CANDIDATOS";
export const DESCARGA_CANDIDATOS_EXITOS = "DESCARGA_CANDIDATOS_EXITOS";
export const DESCARGA_CANDIDATOS_ERROR = "DESCARGA_CANDIDATOS_ERROR";
export const OBTENER_CANDIDATO_ELIMINAR = "OBTENER_CANDIDATO_ELIMINAR";
export const OBTENER_CANDIDATO_EDITAR = "OBTENER_CANDIDATO_EDITAR";
export const COMENZAR_EDICION_CANDIDATO = "COMENZAR_EDICION_CANDIDATO";
export const CANDIDATO_EDITADO_EXITO = "CANDIDATO_EDITADO_EXITO";
export const CANDIDATO_EDITADO_ERROR = "CANDIDATO_EDITADO_ERROR";
export const CANDIDATO_ELIMINADO_EXITO = "CANDIDATO_ELIMINADO_EXITO";
export const CANDIDATO_ELIMINADO_ERROR = "CANDIDATO_ELIMINADO_ERROR";

//USUARIOS
export const AGREGAR_USUARIO = "AGREGAR_USUARIO";
export const AGREGAR_USUARIO_EXITO = "AGREGAR_USUARIO_EXITO";
export const AGREGAR_USUARIO_ERROR = "AGREGAR_USUARIO_ERROR";
export const COMENZAR_DESCARGA_USUARIOS = "COMENZAR_DESCARGA_USUARIOS";
export const DESCARGA_USUARIOS_EXITOS = "DESCARGA_USUARIOS_EXITOS";
export const DESCARGA_USUARIOS_ERROR = "DESCARGA_USUARIOS_ERROR";
export const OBTENER_USUARIO_ELIMINAR = "OBTENER_USUARIO_ELIMINAR";
export const USUARIO_ELIMINADO_EXITO = "USUARIO_ELIMINADO_EXITO";
export const USUARIO_ELIMINADO_ERROR = "USUARIO_ELIMINADO_ERROR";
export const COMENZAR_EDICION_USUARIO = "COMENZAR_EDICION_USUARIO";
export const USUARIO_EDITADO_EXITO = "USUARIO_EDITADO_EXITO";
export const USUARIO_EDITADO_ERROR = "USUARIO_EDITADO_ERROR";
export const OBTENER_USUARIO_EDITAR = "OBTENER_PRODUCTO_EDITAR";

//CANDIDATOS
export const AGREGAR_COMPETENCIA = "AGREGAR_COMPETENCIA";
export const AGREGAR_COMPETENCIA_EXITO = "AGREGAR_COMPETENCIA_EXITO";
export const AGREGAR_COMPETENCIA_ERROR = "AGREGAR_COMPETENCIA_ERROR";
export const COMENZAR_DESCARGA_COMPETENCIAS = "COMENZAR_DESCARGA_COMPETENCIAS";
export const DESCARGA_COMPETENCIAS_EXITOS = "DESCARGA_COMPETENCIAS_EXITOS";
export const DESCARGA_COMPETENCIAS_ERROR = "DESCARGA_COMPETENCIAS_ERROR";
export const OBTENER_COMPETENCIA_ELIMINAR = "OBTENER_COMPETENCIA_ELIMINAR";
export const COMPETENCIA_ELIMINADO_EXITO = "COMPETENCIA_ELIMINADO_EXITO";
export const COMPETENCIA_ELIMINADO_ERROR = "COMPETENCIA_ELIMINADO_ERROR";
export const COMENZAR_EDICION_COMPETENCIA = "COMENZAR_EDICION_COMPETENCIA";
export const COMPETENCIA_EDITADO_EXITO = "COMPETENCIA_EDITADO_EXITO";
export const COMPETENCIA_EDITADO_ERROR = "COMPETENCIA_EDITADO_ERROR";
export const OBTENER_COMPETENCIA_EDITAR = "OBTENER_COMPETENCIA_EDITAR";
